2024-08-14 18:08:53,389 - INFO - div tokens downloaded successfully
2024-08-14 18:09:03,717 - INFO - div tokens downloaded successfully
2024-08-14 18:09:14,063 - INFO - div tokens downloaded successfully
2024-08-14 18:09:24,504 - INFO - div tokens downloaded successfully
2024-08-14 18:09:35,258 - INFO - div tokens downloaded successfully
2024-08-14 18:09:45,908 - INFO - div tokens downloaded successfully
2024-08-14 18:09:56,458 - INFO - div tokens downloaded successfully
2024-08-14 18:10:06,865 - INFO - div tokens downloaded successfully
2024-08-14 18:10:17,099 - INFO - div tokens downloaded successfully
2024-08-14 18:10:27,347 - INFO - div tokens downloaded successfully
2024-08-14 18:10:37,807 - INFO - div tokens downloaded successfully
2024-08-14 18:10:48,083 - INFO - div tokens downloaded successfully
2024-08-14 18:10:58,829 - INFO - div tokens downloaded successfully
2024-08-14 18:11:09,222 - INFO - div tokens downloaded successfully
2024-08-14 18:11:19,722 - INFO - div tokens downloaded successfully
2024-08-14 18:11:29,934 - INFO - div tokens downloaded successfully
2024-08-14 18:11:40,164 - INFO - div tokens downloaded successfully
2024-08-14 18:11:50,447 - INFO - div tokens downloaded successfully
2024-08-14 18:12:00,654 - INFO - div tokens downloaded successfully
2024-08-14 18:12:11,265 - INFO - div tokens downloaded successfully
2024-08-14 18:12:21,736 - INFO - div tokens downloaded successfully
2024-08-14 18:12:31,969 - INFO - div tokens downloaded successfully
2024-08-14 18:12:42,338 - INFO - div tokens downloaded successfully
2024-08-14 18:12:52,604 - INFO - div tokens downloaded successfully
2024-08-14 18:13:02,857 - INFO - div tokens downloaded successfully
2024-08-14 18:13:13,078 - INFO - div tokens downloaded successfully
2024-08-14 18:13:23,482 - INFO - div tokens downloaded successfully
2024-08-14 18:13:33,961 - INFO - div tokens downloaded successfully
2024-08-14 18:13:44,377 - INFO - div tokens downloaded successfully
2024-08-14 18:13:54,809 - INFO - div tokens downloaded successfully
2024-08-14 18:14:05,016 - INFO - div tokens downloaded successfully
2024-08-14 18:14:15,226 - INFO - div tokens downloaded successfully
2024-08-14 18:14:25,458 - INFO - div tokens downloaded successfully
2024-08-14 18:14:35,706 - INFO - div tokens downloaded successfully
2024-08-14 18:14:45,933 - INFO - div tokens downloaded successfully
2024-08-14 18:14:56,567 - INFO - div tokens downloaded successfully
2024-08-14 18:15:06,945 - INFO - div tokens downloaded successfully
2024-08-14 18:15:17,357 - INFO - div tokens downloaded successfully
2024-08-14 18:15:27,943 - INFO - div tokens downloaded successfully
2024-08-14 18:15:38,678 - INFO - div tokens downloaded successfully
2024-08-14 18:15:48,939 - INFO - div tokens downloaded successfully
2024-08-14 18:15:59,183 - INFO - div tokens downloaded successfully
2024-08-14 18:16:09,468 - INFO - div tokens downloaded successfully
2024-08-14 18:16:20,141 - INFO - div tokens downloaded successfully
2024-08-14 18:16:30,378 - INFO - div tokens downloaded successfully
2024-08-14 18:16:40,754 - INFO - div tokens downloaded successfully
2024-08-14 18:16:51,119 - INFO - div tokens downloaded successfully
2024-08-14 18:17:01,459 - INFO - div tokens downloaded successfully
2024-08-14 18:17:11,683 - INFO - div tokens downloaded successfully
2024-08-14 18:17:21,914 - INFO - div tokens downloaded successfully
2024-08-14 18:17:32,124 - INFO - div tokens downloaded successfully
2024-08-14 18:17:42,474 - INFO - div tokens downloaded successfully
2024-08-14 18:17:52,954 - INFO - div tokens downloaded successfully
2024-08-14 18:18:03,676 - INFO - div tokens downloaded successfully
2024-08-14 18:18:14,151 - INFO - div tokens downloaded successfully
2024-08-14 18:18:24,598 - INFO - div tokens downloaded successfully
2024-08-14 18:18:34,828 - INFO - div tokens downloaded successfully
2024-08-14 18:18:45,066 - INFO - div tokens downloaded successfully
2024-08-14 18:18:55,302 - INFO - div tokens downloaded successfully
2024-08-14 18:19:06,045 - INFO - div tokens downloaded successfully
2024-08-14 18:19:16,510 - INFO - div tokens downloaded successfully
2024-08-14 18:19:26,791 - INFO - div tokens downloaded successfully
2024-08-14 18:19:37,101 - INFO - div tokens downloaded successfully
2024-08-14 18:19:48,137 - INFO - div tokens downloaded successfully
2024-08-14 18:19:58,505 - INFO - div tokens downloaded successfully
2024-08-14 18:20:08,771 - INFO - div tokens downloaded successfully
2024-08-14 18:20:19,008 - INFO - div tokens downloaded successfully
2024-08-14 18:20:29,628 - INFO - div tokens downloaded successfully
2024-08-14 18:20:39,976 - INFO - div tokens downloaded successfully
2024-08-14 18:20:50,815 - INFO - div tokens downloaded successfully
2024-08-14 18:21:01,292 - INFO - div tokens downloaded successfully
2024-08-14 18:21:11,706 - INFO - div tokens downloaded successfully
2024-08-14 18:21:22,110 - INFO - div tokens downloaded successfully
2024-08-14 18:21:32,297 - INFO - div tokens downloaded successfully
2024-08-14 18:21:42,557 - INFO - div tokens downloaded successfully
2024-08-14 18:21:53,206 - INFO - div tokens downloaded successfully
2024-08-14 18:22:03,652 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-14 18:22:13,900 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:49:22,808 - INFO - div tokens downloaded successfully
2024-08-27 13:49:33,578 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:49:43,841 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:49:54,182 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:50:04,909 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:50:15,690 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:50:26,106 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:50:36,615 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:50:47,288 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:50:57,493 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:51:08,191 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:51:18,669 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:51:29,033 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:51:39,540 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:51:49,988 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:52:00,312 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:52:10,547 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:52:21,057 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:52:31,394 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:52:41,638 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:52:51,897 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:53:02,150 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:53:12,377 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:53:22,608 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:53:32,857 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:53:43,168 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:53:53,448 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:54:03,847 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:54:14,212 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:54:24,491 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:54:35,235 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:54:45,656 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:54:55,959 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:55:06,525 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:55:16,902 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:55:28,961 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:55:39,160 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:55:49,547 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:56:00,014 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:56:10,226 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:56:20,513 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:56:31,011 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:56:41,769 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:56:52,049 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:57:02,358 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:57:12,980 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:57:23,477 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:57:33,723 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:57:44,108 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:57:54,342 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:58:04,837 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:58:15,109 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:58:26,439 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:58:36,690 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:58:47,044 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:58:57,496 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:59:08,138 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:59:18,602 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:59:29,395 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:59:39,956 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 13:59:50,294 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:00:01,053 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:00:11,672 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:00:21,880 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:00:32,665 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:00:42,931 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:00:53,544 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:01:04,297 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:01:15,327 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:01:26,252 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:01:36,855 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:01:48,217 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:01:58,870 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:02:09,368 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:02:20,179 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:02:31,049 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:02:41,992 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:02:52,439 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:03:03,008 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:03:13,326 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:03:23,641 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:03:33,931 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:03:44,852 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:03:55,157 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:04:05,894 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:04:16,609 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:04:26,973 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:04:37,539 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:04:48,303 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:04:59,033 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:05:09,753 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:05:20,806 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:05:31,510 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:05:42,030 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:05:52,483 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:06:03,198 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:06:13,516 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:06:24,122 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:06:34,869 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:06:47,129 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:06:57,603 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:07:08,210 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:07:18,746 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:07:29,529 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:07:40,274 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:07:50,956 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:08:01,792 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:08:12,549 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:08:23,010 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:08:33,296 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:08:43,898 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:08:54,328 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:09:05,382 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:09:15,961 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:09:26,581 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:09:37,024 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:09:47,852 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:09:58,116 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:10:08,671 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:10:19,112 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:10:29,373 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:10:39,820 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:10:50,740 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:11:01,505 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:11:12,400 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:11:22,955 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:11:33,450 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:11:44,200 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:11:55,227 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:12:05,947 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:12:16,451 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:12:27,019 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:12:37,927 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:12:48,408 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:12:58,759 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:13:09,287 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:13:20,028 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:13:30,926 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:13:41,527 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:13:52,559 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:14:02,839 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:14:13,271 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:14:23,918 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:14:34,521 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:14:45,121 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:14:55,857 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:15:06,297 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:15:16,998 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:15:27,495 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:15:38,247 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:15:48,578 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:16:00,643 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:16:11,005 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:16:21,838 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:16:32,608 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:16:43,370 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:16:53,804 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:17:04,064 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:17:14,668 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:17:24,881 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:17:35,426 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:17:45,674 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:17:55,975 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:18:06,297 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:18:16,575 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:18:27,166 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:18:37,452 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:18:47,867 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:18:58,144 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:19:11,030 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:19:21,798 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:19:32,143 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:19:42,735 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:19:53,454 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:20:04,184 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:20:14,449 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:20:24,656 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:20:35,238 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:20:45,476 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:20:56,569 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:21:06,843 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:21:17,079 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:21:27,283 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:21:37,675 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:21:48,178 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:21:59,075 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:22:09,256 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:22:20,004 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:22:30,477 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:22:40,916 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:22:51,354 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:23:01,839 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:23:12,553 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:23:23,034 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:23:34,070 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:23:44,537 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:23:55,069 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:24:05,346 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:24:15,549 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:24:25,771 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:24:36,086 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:24:46,814 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:24:57,787 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:25:08,003 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:25:18,447 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:25:29,183 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:25:39,631 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:25:49,875 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:26:00,790 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:26:11,230 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:26:21,884 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:26:32,395 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:26:42,922 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:26:53,127 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:27:03,413 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:27:13,639 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:27:23,932 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:27:34,559 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:27:45,018 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:27:55,463 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:28:05,914 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:28:16,362 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:28:26,816 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:28:37,032 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:28:47,275 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:28:57,506 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:29:07,734 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:29:18,114 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:29:28,556 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:29:39,022 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:29:49,349 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:29:59,857 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:30:10,345 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:30:20,647 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:30:30,929 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:30:41,668 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:30:53,824 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:31:04,711 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:31:15,457 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:31:26,227 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:31:36,675 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:31:47,106 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:31:57,345 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:32:08,071 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:32:18,507 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:32:28,951 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:32:39,184 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:32:49,414 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:32:59,699 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:33:10,088 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:33:20,499 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:33:30,907 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:33:41,327 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:33:51,792 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:34:02,207 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:34:12,670 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:34:22,995 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:34:33,515 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:34:43,982 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:34:53,998 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 666, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1001, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f42154d9430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.divar.ir', port=443): Max retries exceeded with url: /v8/postlist/w/search (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f42154d9430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 59, in <module>
    response = requests.post(url, json= payload)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 535, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 648, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.divar.ir', port=443): Max retries exceeded with url: /v8/postlist/w/search (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f42154d9430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2024-08-27 14:35:14,813 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 666, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1001, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f42154d9ac0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.divar.ir', port=443): Max retries exceeded with url: /v8/postlist/w/search (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f42154d9ac0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 59, in <module>
    response = requests.post(url, json= payload)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 535, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 648, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.divar.ir', port=443): Max retries exceeded with url: /v8/postlist/w/search (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f42154d9ac0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2024-08-27 14:35:25,408 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
2024-08-27 14:35:36,428 - ERROR - CAN NOT  DOWNLOAD DIV TOKENS!
ERORR:
Traceback (most recent call last):
  File "/home/sjd/Desktop/Realstate-Ads-Data-divar-sheypoor-/sc_ads/scraper/div_sc.py", line 81, in <module>
    print(f"{myfile} exists.")
OSError: [Errno 5] Input/output error
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2024-09-03 14:23:13,650 - INFO - div tokens downloaded successfully
2024-09-03 14:32:27,013 - INFO - div tokens downloaded successfully
2024-09-03 14:33:31,018 - INFO - div tokens downloaded successfully
2024-09-03 14:35:54,608 - INFO - div tokens downloaded successfully
2024-09-03 14:37:45,643 - INFO - div tokens downloaded successfully
2024-09-03 14:38:08,015 - INFO - div tokens downloaded successfully
2024-09-03 14:38:25,673 - INFO - div tokens downloaded successfully
2024-09-03 15:35:48,541 - INFO - div tokens downloaded successfully
2024-09-03 15:36:25,379 - INFO - div tokens downloaded successfully
2024-09-03 15:36:32,217 - INFO - div tokens downloaded successfully
2024-09-03 15:36:49,906 - INFO - div tokens downloaded successfully
2024-09-03 15:37:10,415 - INFO - div tokens downloaded successfully
2024-09-03 15:37:35,121 - INFO - div tokens downloaded successfully
2024-09-03 15:38:28,962 - INFO - div tokens downloaded successfully
2024-09-03 15:38:34,384 - INFO - div tokens downloaded successfully
2024-09-03 15:38:40,964 - INFO - div tokens downloaded successfully
2024-09-03 15:38:57,555 - INFO - div tokens downloaded successfully
2024-09-03 15:39:14,752 - INFO - div tokens downloaded successfully
2024-09-03 15:39:28,137 - INFO - div tokens downloaded successfully
2024-09-03 15:39:33,799 - INFO - div tokens downloaded successfully
2024-09-03 15:39:39,562 - INFO - div tokens downloaded successfully
2024-09-03 15:39:57,093 - INFO - div tokens downloaded successfully
2024-09-03 15:41:00,300 - INFO - div tokens downloaded successfully
2024-09-03 15:41:28,648 - INFO - div tokens downloaded successfully
2024-09-03 15:41:40,464 - INFO - div tokens downloaded successfully
2024-09-03 16:02:59,631 - INFO - div tokens downloaded successfully
2024-09-03 16:03:32,209 - INFO - div tokens downloaded successfully
2024-09-03 16:03:46,476 - INFO - div tokens downloaded successfully
2024-09-03 17:15:29,091 - INFO - div tokens downloaded successfully
2024-09-03 17:17:16,254 - INFO - div tokens downloaded successfully
2024-09-03 17:17:36,789 - INFO - div tokens downloaded successfully
2024-09-03 17:18:06,248 - INFO - div tokens downloaded successfully
2024-09-07 12:48:46,227 - INFO - div tokens downloaded successfully
2024-09-07 12:48:49,749 - INFO - div tokens downloaded successfully
2024-09-07 12:48:53,754 - INFO - div tokens downloaded successfully
2024-09-07 12:48:57,166 - INFO - div tokens downloaded successfully
2024-09-07 12:49:00,776 - INFO - div tokens downloaded successfully
2024-09-07 12:49:04,525 - INFO - div tokens downloaded successfully
2024-09-07 12:49:08,057 - INFO - div tokens downloaded successfully
2024-09-07 12:49:11,718 - INFO - div tokens downloaded successfully
2024-09-07 12:49:15,211 - INFO - div tokens downloaded successfully
2024-09-07 15:36:32,682 - INFO - div tokens downloaded successfully
2024-09-07 15:36:47,867 - INFO - div tokens downloaded successfully
2024-09-07 15:37:11,312 - INFO - div tokens downloaded successfully
2024-09-09 11:13:54,795 - INFO - div tokens downloaded successfully
2024-09-09 11:13:55,275 - INFO - sheyp tokens downloaded successfully
2024-09-09 11:13:55,278 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:13:55,279 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37074), raddr=('127.0.0.1', 5672)>
2024-09-09 11:13:55,281 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f9168b31030>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f9168b31030> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:13:55,288 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37074), raddr=('127.0.0.1', 5672)>
2024-09-09 11:13:55,288 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37074), raddr=('127.0.0.1', 5672)>
2024-09-09 11:13:55,289 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37074), raddr=('127.0.0.1', 5672)>
2024-09-09 11:13:55,289 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=None; pending-error=ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
2024-09-09 11:13:55,289 - ERROR - Connection closed while authenticating indicating a probable authentication error
2024-09-09 11:13:55,289 - INFO - Connection setup terminated due to ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2024-09-09 11:13:55,290 - ERROR - AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2024-09-09 11:13:55,290 - ERROR - AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - None.
2024-09-09 11:13:55,290 - ERROR - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - None
2024-09-09 11:13:55,291 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37074), raddr=('127.0.0.1', 5672)>
2024-09-09 11:13:55,291 - ERROR - Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - None
2024-09-09 11:13:55,291 - ERROR - Error in _create_connection().
Traceback (most recent call last):
  File "/home/sjd/.local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.ProbableAuthenticationError: ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
2024-09-09 11:23:20,754 - INFO - div tokens downloaded successfully
2024-09-09 11:23:21,299 - INFO - sheyp tokens downloaded successfully
2024-09-09 11:23:21,305 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:23:21,306 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33666), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:21,308 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f80f2f44fd0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f80f2f44fd0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:23:21,314 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f80f2f44fd0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:21,314 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f80f2f44fd0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:21,314 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f80f2f44fd0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:21,315 - INFO - Created channel=1
2024-09-09 11:23:21,406 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:23:21,407 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f80f2f44fd0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:21,408 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f80f2f44fd0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:21,409 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:23:21,409 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33666), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:21,410 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33666), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:21,410 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33666), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:21,410 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:21,411 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:21,411 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33666), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:21,411 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:23:21,414 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:23:21,414 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33672), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:21,415 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d73c40>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d73c40> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:23:21,418 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d73c40> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:21,419 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d73c40> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:21,419 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d73c40> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:21,420 - INFO - Created channel=1
2024-09-09 11:23:21,474 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:23:21,474 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d73c40> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:21,475 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d73c40> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:21,475 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:23:21,476 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33672), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:21,476 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33672), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:21,476 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33672), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:21,477 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:21,477 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:21,477 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33672), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:21,478 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:23:32,063 - INFO - div tokens downloaded successfully
2024-09-09 11:23:32,636 - INFO - sheyp tokens downloaded successfully
2024-09-09 11:23:32,639 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:23:32,640 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 50736), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:32,641 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d724d0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d724d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:23:32,645 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d724d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:32,646 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d724d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:32,646 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d724d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:32,647 - INFO - Created channel=1
2024-09-09 11:23:32,657 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:23:32,657 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d724d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:32,658 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d724d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:32,658 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:23:32,659 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 50736), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:32,659 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 50736), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:32,659 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 50736), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:32,660 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:32,660 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:32,660 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 50736), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:32,660 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:23:32,662 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:23:32,663 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 50738), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:32,664 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d73b50>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d73b50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:23:32,667 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d73b50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:32,667 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d73b50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:32,667 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d73b50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:32,668 - INFO - Created channel=1
2024-09-09 11:23:32,674 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:23:32,674 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d73b50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:32,675 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d73b50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:32,675 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:23:32,676 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 50738), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:32,677 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 50738), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:32,677 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 50738), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:32,677 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:32,677 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:32,677 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 50738), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:32,678 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:23:43,181 - INFO - div tokens downloaded successfully
2024-09-09 11:23:43,736 - INFO - sheyp tokens downloaded successfully
2024-09-09 11:23:43,738 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:23:43,739 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 49686), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:43,740 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d72cb0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d72cb0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:23:43,744 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d72cb0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:43,744 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d72cb0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:43,745 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d72cb0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:43,745 - INFO - Created channel=1
2024-09-09 11:23:43,756 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:23:43,756 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d72cb0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:43,757 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d72cb0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:43,757 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:23:43,758 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 49686), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:43,758 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 49686), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:43,759 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 49686), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:43,759 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:43,759 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:43,759 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 49686), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:43,759 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:23:43,762 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:23:43,763 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 49698), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:43,764 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d70df0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d70df0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:23:43,768 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d70df0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:43,768 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d70df0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:43,768 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d70df0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:43,769 - INFO - Created channel=1
2024-09-09 11:23:43,775 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:23:43,775 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d70df0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:43,776 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d70df0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:43,777 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:23:43,778 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 49698), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:43,778 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 49698), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:43,778 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 49698), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:43,779 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:43,779 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:43,779 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 49698), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:43,780 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:23:54,339 - INFO - div tokens downloaded successfully
2024-09-09 11:23:54,682 - INFO - sheyp tokens downloaded successfully
2024-09-09 11:23:54,684 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:23:54,684 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 38782), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:54,685 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d706a0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d706a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:23:54,688 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d706a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:54,688 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d706a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:54,689 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d706a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:54,689 - INFO - Created channel=1
2024-09-09 11:23:54,700 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:23:54,700 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d706a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:54,701 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d706a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:54,702 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:23:54,703 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 38782), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:54,703 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 38782), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:54,703 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 38782), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:54,703 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:54,703 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:54,704 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 38782), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:54,704 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:23:54,706 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:23:54,707 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 38798), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:54,708 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6e560>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6e560> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:23:54,711 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6e560> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:54,712 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6e560> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:54,712 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6e560> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:23:54,713 - INFO - Created channel=1
2024-09-09 11:23:54,718 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:23:54,718 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6e560> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:54,719 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6e560> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:23:54,719 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:23:54,720 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 38798), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:54,720 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 38798), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:54,720 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 38798), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:54,720 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:54,721 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:23:54,721 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 38798), raddr=('127.0.0.1', 5672)>
2024-09-09 11:23:54,721 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:24:05,323 - INFO - div tokens downloaded successfully
2024-09-09 11:24:05,783 - INFO - sheyp tokens downloaded successfully
2024-09-09 11:24:05,784 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:24:05,785 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37114), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:05,786 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6dea0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6dea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:24:05,789 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6dea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:05,789 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6dea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:05,790 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6dea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:05,790 - INFO - Created channel=1
2024-09-09 11:24:05,798 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:24:05,799 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6dea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:05,800 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6dea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:05,800 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:24:05,801 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37114), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:05,801 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37114), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:05,802 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37114), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:05,802 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:05,802 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:05,802 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37114), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:05,802 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:24:05,804 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:24:05,805 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37126), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:05,805 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6dc60>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6dc60> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:24:05,809 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6dc60> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:05,809 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6dc60> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:05,809 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6dc60> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:05,810 - INFO - Created channel=1
2024-09-09 11:24:05,816 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:24:05,816 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6dc60> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:05,817 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6dc60> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:05,817 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:24:05,817 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37126), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:05,818 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37126), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:05,818 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37126), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:05,818 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:05,818 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:05,818 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37126), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:05,818 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:24:16,322 - INFO - div tokens downloaded successfully
2024-09-09 11:24:16,885 - INFO - sheyp tokens downloaded successfully
2024-09-09 11:24:16,887 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:24:16,887 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 55202), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:16,888 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6e140>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6e140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:24:16,892 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6e140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:16,892 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6e140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:16,892 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6e140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:16,893 - INFO - Created channel=1
2024-09-09 11:24:16,904 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:24:16,904 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6e140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:16,905 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6e140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:16,905 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:24:16,906 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 55202), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:16,906 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 55202), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:16,906 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 55202), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:16,907 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:16,907 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:16,907 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 55202), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:16,907 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:24:16,909 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:24:16,910 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 55216), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:16,911 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6fb50>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6fb50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:24:16,914 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6fb50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:16,915 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6fb50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:16,915 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6fb50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:16,915 - INFO - Created channel=1
2024-09-09 11:24:16,920 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:24:16,920 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6fb50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:16,921 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8101d6fb50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:16,922 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:24:16,922 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 55216), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:16,923 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 55216), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:16,923 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 55216), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:16,924 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:16,924 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:16,924 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 55216), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:16,925 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:24:37,288 - INFO - div tokens downloaded successfully
2024-09-09 11:24:37,830 - INFO - sheyp tokens downloaded successfully
2024-09-09 11:24:37,832 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:24:37,833 - INFO - Socket connected: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33620), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:37,834 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0d300>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0d300> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:24:37,837 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0d300> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:37,837 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0d300> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:37,838 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0d300> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:37,838 - INFO - Created channel=1
2024-09-09 11:24:38,048 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:24:38,048 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0d300> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:38,050 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0d300> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:38,051 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:24:38,053 - INFO - Aborting transport connection: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33620), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:38,053 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33620), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:38,053 - INFO - Deactivating transport: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33620), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:38,054 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:38,054 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:38,055 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33620), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:38,055 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:24:38,059 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:24:38,061 - INFO - Socket connected: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33626), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:38,062 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0cee0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0cee0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:24:38,071 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0cee0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:38,071 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0cee0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:38,072 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0cee0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:38,073 - INFO - Created channel=1
2024-09-09 11:24:38,212 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:24:38,213 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0cee0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:38,215 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0cee0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:38,215 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:24:38,217 - INFO - Aborting transport connection: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33626), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:38,217 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33626), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:38,217 - INFO - Deactivating transport: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33626), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:38,218 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:38,218 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:38,218 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 33626), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:38,219 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:24:48,442 - INFO - div tokens downloaded successfully
2024-09-09 11:24:48,846 - INFO - sheyp tokens downloaded successfully
2024-09-09 11:24:48,848 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:24:48,848 - INFO - Socket connected: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 51902), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:48,849 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0f1c0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0f1c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:24:48,851 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0f1c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:48,852 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0f1c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:48,852 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0f1c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:48,852 - INFO - Created channel=1
2024-09-09 11:24:48,857 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:24:48,857 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0f1c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:48,858 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0f1c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:48,858 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:24:48,858 - INFO - Aborting transport connection: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 51902), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:48,859 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 51902), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:48,859 - INFO - Deactivating transport: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 51902), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:48,859 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:48,859 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:48,859 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 51902), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:48,859 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:24:48,861 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:24:48,861 - INFO - Socket connected: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 51912), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:48,862 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf4070>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf4070> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:24:48,866 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf4070> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:48,867 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf4070> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:48,867 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf4070> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:48,867 - INFO - Created channel=1
2024-09-09 11:24:48,870 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:24:48,870 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf4070> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:48,871 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf4070> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:48,871 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:24:48,872 - INFO - Aborting transport connection: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 51912), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:48,872 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 51912), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:48,872 - INFO - Deactivating transport: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 51912), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:48,872 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:48,872 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:48,872 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 51912), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:48,873 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:24:59,148 - INFO - div tokens downloaded successfully
2024-09-09 11:24:59,484 - INFO - sheyp tokens downloaded successfully
2024-09-09 11:24:59,486 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:24:59,486 - INFO - Socket connected: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 48060), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:59,487 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf5930>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf5930> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:24:59,490 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf5930> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:59,490 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf5930> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:59,490 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf5930> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:59,490 - INFO - Created channel=1
2024-09-09 11:24:59,497 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:24:59,497 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf5930> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:59,498 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf5930> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:59,498 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:24:59,498 - INFO - Aborting transport connection: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 48060), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:59,498 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 48060), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:59,499 - INFO - Deactivating transport: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 48060), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:59,499 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:59,499 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:59,499 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 48060), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:59,500 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:24:59,501 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:24:59,501 - INFO - Socket connected: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 48070), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:59,502 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf5cc0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf5cc0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:24:59,506 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf5cc0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:59,506 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf5cc0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:59,506 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf5cc0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:24:59,507 - INFO - Created channel=1
2024-09-09 11:24:59,510 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:24:59,510 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf5cc0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:59,511 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf5cc0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:24:59,511 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:24:59,512 - INFO - Aborting transport connection: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 48070), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:59,512 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 48070), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:59,512 - INFO - Deactivating transport: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 48070), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:59,512 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:59,513 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:24:59,513 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 48070), raddr=('127.0.0.1', 5672)>
2024-09-09 11:24:59,513 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:25:10,059 - INFO - div tokens downloaded successfully
2024-09-09 11:25:10,504 - INFO - sheyp tokens downloaded successfully
2024-09-09 11:25:10,505 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:25:10,506 - INFO - Socket connected: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 45526), raddr=('127.0.0.1', 5672)>
2024-09-09 11:25:10,506 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0f430>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0f430> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:25:10,510 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0f430> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:25:10,510 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0f430> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:25:10,510 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0f430> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:25:10,511 - INFO - Created channel=1
2024-09-09 11:25:10,517 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:25:10,517 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0f430> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:25:10,518 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cc0f430> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:25:10,518 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:25:10,519 - INFO - Aborting transport connection: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 45526), raddr=('127.0.0.1', 5672)>
2024-09-09 11:25:10,519 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 45526), raddr=('127.0.0.1', 5672)>
2024-09-09 11:25:10,519 - INFO - Deactivating transport: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 45526), raddr=('127.0.0.1', 5672)>
2024-09-09 11:25:10,519 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:25:10,520 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:25:10,520 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 45526), raddr=('127.0.0.1', 5672)>
2024-09-09 11:25:10,520 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-09 11:25:10,521 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-09 11:25:10,521 - INFO - Socket connected: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 45536), raddr=('127.0.0.1', 5672)>
2024-09-09 11:25:10,522 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf4820>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf4820> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-09 11:25:10,525 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf4820> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:25:10,526 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf4820> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:25:10,526 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf4820> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-09 11:25:10,526 - INFO - Created channel=1
2024-09-09 11:25:10,530 - INFO - Closing connection (200): Normal shutdown
2024-09-09 11:25:10,530 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf4820> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:25:10,531 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7b5cbf4820> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-09 11:25:10,531 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-09 11:25:10,531 - INFO - Aborting transport connection: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 45536), raddr=('127.0.0.1', 5672)>
2024-09-09 11:25:10,532 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 45536), raddr=('127.0.0.1', 5672)>
2024-09-09 11:25:10,532 - INFO - Deactivating transport: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 45536), raddr=('127.0.0.1', 5672)>
2024-09-09 11:25:10,532 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:25:10,532 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-09 11:25:10,532 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 45536), raddr=('127.0.0.1', 5672)>
2024-09-09 11:25:10,532 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-10 13:45:11,379 - INFO - div tokens downloaded successfully
2024-09-10 13:45:12,161 - INFO - sheyp tokens downloaded successfully
2024-09-10 13:45:12,165 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-10 13:45:12,166 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 39802), raddr=('127.0.0.1', 5672)>
2024-09-10 13:45:12,168 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f265805d030>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f265805d030> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-10 13:45:12,171 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 39802), raddr=('127.0.0.1', 5672)>
2024-09-10 13:45:12,171 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 39802), raddr=('127.0.0.1', 5672)>
2024-09-10 13:45:12,172 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 39802), raddr=('127.0.0.1', 5672)>
2024-09-10 13:45:12,172 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=None; pending-error=ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
2024-09-10 13:45:12,172 - ERROR - Connection closed while authenticating indicating a probable authentication error
2024-09-10 13:45:12,173 - INFO - Connection setup terminated due to ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2024-09-10 13:45:12,173 - ERROR - AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2024-09-10 13:45:12,173 - ERROR - AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - None.
2024-09-10 13:45:12,174 - ERROR - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - None
2024-09-10 13:45:12,174 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 39802), raddr=('127.0.0.1', 5672)>
2024-09-10 13:45:12,174 - ERROR - Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - None
2024-09-10 13:45:12,174 - ERROR - Error in _create_connection().
Traceback (most recent call last):
  File "/home/sjd/.local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.ProbableAuthenticationError: ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
2024-09-10 13:47:54,594 - INFO - div tokens downloaded successfully
2024-09-10 13:47:55,200 - INFO - sheyp tokens downloaded successfully
2024-09-10 13:47:55,203 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-10 13:47:55,204 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 52608), raddr=('127.0.0.1', 5672)>
2024-09-10 13:47:55,206 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f03e40701c0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f03e40701c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-10 13:47:55,211 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f03e40701c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-10 13:47:55,212 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f03e40701c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-10 13:47:55,212 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f03e40701c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-10 13:47:55,214 - INFO - Created channel=1
2024-09-10 13:47:55,354 - INFO - Closing connection (200): Normal shutdown
2024-09-10 13:47:55,355 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f03e40701c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-10 13:47:55,355 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f03e40701c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-10 13:47:55,356 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-10 13:47:55,356 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 52608), raddr=('127.0.0.1', 5672)>
2024-09-10 13:47:55,356 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 52608), raddr=('127.0.0.1', 5672)>
2024-09-10 13:47:55,357 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 52608), raddr=('127.0.0.1', 5672)>
2024-09-10 13:47:55,357 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-10 13:47:55,357 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-10 13:47:55,357 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 52608), raddr=('127.0.0.1', 5672)>
2024-09-10 13:47:55,358 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-09-10 13:47:55,360 - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-09-10 13:47:55,360 - INFO - Socket connected: <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 52614), raddr=('127.0.0.1', 5672)>
2024-09-10 13:47:55,361 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f03e4071ea0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f03e4071ea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-09-10 13:47:55,364 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f03e4071ea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-10 13:47:55,364 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f03e4071ea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-10 13:47:55,364 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f03e4071ea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-09-10 13:47:55,365 - INFO - Created channel=1
2024-09-10 13:47:55,436 - INFO - Closing connection (200): Normal shutdown
2024-09-10 13:47:55,436 - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f03e4071ea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-10 13:47:55,437 - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f03e4071ea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-09-10 13:47:55,437 - INFO - Closing connection (200): 'Normal shutdown'
2024-09-10 13:47:55,438 - INFO - Aborting transport connection: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 52614), raddr=('127.0.0.1', 5672)>
2024-09-10 13:47:55,438 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 52614), raddr=('127.0.0.1', 5672)>
2024-09-10 13:47:55,438 - INFO - Deactivating transport: state=1; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 52614), raddr=('127.0.0.1', 5672)>
2024-09-10 13:47:55,438 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-10 13:47:55,438 - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-09-10 13:47:55,439 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 52614), raddr=('127.0.0.1', 5672)>
2024-09-10 13:47:55,439 - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
